[package]
name = "mk_desktop"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.9", features = ["derive"] }
confy = {version = "0.4"}
serde = { version = "1.0", features = ["derive"] }
